name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies
          restore-keys: |
            ${{ runner.os }}-dependencies

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage --passWithNoTests

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverageact -j testact -j test